# Generated by Django 6.0.3 on 2026-04-01 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher', 'day'], name='timetable_t_teacher_da3f29_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['class_name', 'section', 'day'], name='timetable_t_class_n_c7efd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('class_name', 'section', 'day', 'start_time')},
        ),
    ]
