# Generated by Django 6.0.3 on 2026-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetableentry_delete_timetable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['day', 'period']},
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='period',
            field=models.IntegerField(choices=[(1, '08:00 AM - 09:00 AM'), (2, '09:00 AM - 10:00 AM'), (3, '10:00 AM - 11:00 AM'), (4, '11:00 AM - 12:00 PM'), (5, '01:00 PM - 02:00 PM'), (6, '02:00 PM - 03:00 PM'), (7, '03:00 PM - 04:00 PM'), (8, '04:00 PM - 05:00 PM')], default=1),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='section',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('class_name', 'section', 'day', 'period')},
        ),
    ]
