# Generated by Django 6.0.3 on 2026-04-01 07:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetableentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('class_name', 'section', 'day', 'period'), ('teacher', 'day', 'period')},
        ),
    ]
