# Generated by Django 6.0.3 on 2026-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_timetableentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='period',
            field=models.IntegerField(choices=[(1, '08:00 AM - 09:00 AM'), (2, '09:00 AM - 10:00 AM'), (3, '10:00 AM - 11:00 AM'), (4, '12:00 PM - 01:00 PM'), (5, '01:00 PM - 02:00 PM'), (6, '02:00 PM - 03:00 PM')], default=1),
        ),
    ]
