# Generated by Django 6.0.3 on 2026-04-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('timetable', '0005_alter_timetableentry_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='tenants.school'),
        ),
    ]
