# Generated by Django 5.2.9 on 2026-04-02 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('timetable', '0006_timetableentry_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('school', 'class_name', 'section', 'day', 'period'), ('school', 'teacher', 'day', 'period')},
        ),
    ]
