# Generated by Django 5.0.3 on 2026-04-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_timetableentry_options_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='shift_ref',
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.shift'),
        ),
    ]
