# Generated by Django 5.0.3 on 2026-04-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_remove_timetableentry_shift_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='shift_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.shift'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift')], default='morning', max_length=20),
        ),
    ]
