# Generated by Django 5.0.3 on 2026-04-16 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_dealer_school_location'),
        ('timetable', '0011_timetableentry_shift_ref_alter_timetableentry_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelOptions(
                    name='timetableentry',
                    options={'ordering': ['shift_ref', 'day', 'period_number']},
                ),
                migrations.AlterUniqueTogether(
                    name='timetableentry',
                    unique_together={
                        ('school', 'class_name', 'section', 'shift_ref', 'day', 'period_number'),
                        ('school', 'teacher', 'shift_ref', 'day', 'period_number')
                    },
                ),
            ],
            database_operations=[
                # Drop stagnant constraints from migration 0007
                migrations.RunSQL(
                    "ALTER TABLE timetable_timetableentry DROP CONSTRAINT IF EXISTS timetable_timetableentry_school_id_class_name_sec_f653a8b5_uniq;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE timetable_timetableentry DROP CONSTRAINT IF EXISTS timetable_timetableentry_school_id_teacher_id_day_period_80d07a16_uniq;"
                ),
                # Add new shift_ref based constraints
                migrations.RunSQL(
                    "ALTER TABLE timetable_timetableentry ADD CONSTRAINT timetable_entry_class_shift_uniq UNIQUE (school_id, class_name, section, shift_ref_id, day, period_number);"
                ),
                migrations.RunSQL(
                    "ALTER TABLE timetable_timetableentry ADD CONSTRAINT timetable_entry_teacher_shift_uniq UNIQUE (school_id, teacher_id, shift_ref_id, day, period_number);"
                ),
            ]
        ),
    ]
