# Generated by Django 5.0.3 on 2026-04-16 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_dealer_school_location'),
        ('timetable', '0011_timetableentry_shift_ref_alter_timetableentry_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelOptions(
                    name='timetableentry',
                    options={'ordering': ['shift_ref', 'day', 'period_number']},
                ),
                migrations.AlterUniqueTogether(
                    name='timetableentry',
                    unique_together={
                        ('school', 'class_name', 'section', 'shift_ref', 'day', 'period_number'),
                        ('school', 'teacher', 'shift_ref', 'day', 'period_number')
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(lambda apps, schema_editor: None, migrations.RunPython.noop),
            ]
        ),
    ]
