# Generated by Django 5.0.3 on 2026-04-16 11:44

from django.db import migrations

def drop_stale_constraint(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE timetable_timetableentry DROP CONSTRAINT IF EXISTS timetable_timetableentry_school_id_teacher_id_day_67c86a88_uniq;")
    elif connection.vendor == 'sqlite':
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_timetableentry_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            drop_stale_constraint,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

