# Generated by Django 6.0.3 on 2026-04-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_profile_image'),
        ('accounts', '0010_remove_user_profile_picture_user_profile_photo'),
    ]

    operations = [
    ]
