# Generated by Django 5.0.3 on 2026-04-01 10:22

from django.db import migrations, models
from django.db.backends.utils import truncate_name


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_blood_group_studentprofile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(
                fields=('class_section', 'roll_number'),
                name='unique_roll_per_class_section',
            ),
        ),
    ]
