# Generated by Django 5.0.3 on 2026-04-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_admissionsequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionSequence',
        ),
    ]
