# Generated by Django 6.0.3 on 2026-04-21 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_mainclass_shift_classsection_assigned_shift'),
        ('students', '0008_drop_old_parent_columns'),
        ('tenants', '0004_remove_school_show_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.school'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('school', 'admission_number'), name='unique_admission_per_school'),
        ),
    ]
