# Generated by Django 5.0.3 on 2026-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_parent_studentprofile_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='school_conduct/profile_photo/'),
        ),
    ]
