# Generated by Django 5.0.3 on 2026-05-03 03:50

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=students.models.student_photo_path),
        ),
    ]
