# Generated by Django 5.0.3 on 2026-07-23 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_mainclass_shift_classsection_assigned_shift'),
        ('students', '0014_studentprofile_assigned_shift'),
        ('tenants', '0007_alter_school_hero_image_alter_school_logo'),
        ('timetable', '0015_shift_flexible_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('school', 'rfid_code'), name='unique_student_rfid_per_school'),
        ),
    ]
