# Generated by Django 6.0.3 on 2026-04-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('tenants', '0004_remove_school_show_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='tenants.school'),
        ),
    ]
