# Generated by Django 5.0.3 on 2026-03-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('classes', '0001_initial'),
        ('students', '0002_studentprofile_blood_group_studentprofile_category_and_more'),
        ('teachers', '0002_teacherprofile_dob_teacherprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classes.classsection'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_section', 'date'], name='attendance__class_s_860ff4_idx'),
        ),
    ]
