# Generated by Django 5.0.3 on 2026-04-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_class_section_and_more'),
        ('attendance', '0002_attendance_verification_fields'),
    ]

    operations = [
    ]
