# Generated by Django 5.0.3 on 2026-06-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_merge_20260401_1604'),
        ('tenants', '0007_alter_school_hero_image_alter_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Gate, Hostel', max_length=100)),
                ('device_ip', models.GenericIPAddressField(default='192.168.0.150')),
                ('device_port', models.IntegerField(default=4370)),
                ('device_password', models.IntegerField(default=0)),
                ('machine_number', models.IntegerField(default=1)),
                ('device_secret_key', models.CharField(default='y0ur_Sup3r_S3cr3t_B1om3tr1c_K3y_987', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='tenants.school')),
            ],
        ),
    ]
