# Generated by Django 5.0.3 on 2026-06-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='serial_number',
            field=models.CharField(blank=True, help_text='The physical Serial Number (SN) of the Team Office machine.', max_length=100, null=True, unique=True),
        ),
    ]
