# Generated by Django 5.0.3 on 2026-06-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_biometriceventlog_and_tcp_device_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='biometriceventlog',
            new_name='attendance__device__a47cac_idx',
            old_name='attendance_b_device__b3c6f7_idx',
        ),
        migrations.RenameIndex(
            model_name='biometriceventlog',
            new_name='attendance__status_92e275_idx',
            old_name='attendance_b_status_6352de_idx',
        ),
        migrations.RenameIndex(
            model_name='biometriceventlog',
            new_name='attendance__event_t_7418d7_idx',
            old_name='attendance_b_event_t_7b6691_idx',
        ),
    ]
