# Generated by Django 5.0.3 on 2026-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_biometricdevice_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevice',
            name='device_ip',
            field=models.CharField(default='192.168.0.150', max_length=255),
        ),
    ]
