# Generated by Django 5.0.3 on 2026-07-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_biometricdevice_device_ip'),
        ('attendance', '0010_reconcile_biometriceventlog_schema'),
    ]

    operations = [
    ]
