# Generated by Django 5.0.3 on 2026-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_merge_20260720_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricdevice',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='device_ip',
            field=models.GenericIPAddressField(default='192.168.0.150'),
        ),
    ]
