# Generated by Django 5.0.3 on 2026-09-17 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_biometricdevice_serial_number_and_more'),
        ('tenants', '0007_alter_school_hero_image_alter_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_late_time', models.TimeField(blank=True, help_text='Punches after this time will be marked as late for teachers', null=True)),
                ('student_late_time', models.TimeField(blank=True, help_text='Punches after this time will be marked as late for students', null=True)),
                ('auto_mark_absent', models.BooleanField(default=True, help_text='Automatically treat unpunched teachers/students as absent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_setting', to='tenants.school')),
            ],
        ),
    ]
