# Generated by Django 6.0.3 on 2026-04-01 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_classsection_school_mainclass_school_and_more'),
        ('students', '0002_studentprofile_blood_group_studentprofile_category_and_more'),
        ('teachers', '0003_teacher_documents'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Unit Test', 'Unit Test'), ('Practical', 'Practical'), ('Other', 'Other')], default='Midterm', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('result_published', models.BooleanField(default=False)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.classsection')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.school')),
            ],
            options={
                'unique_together': {('name', 'class_section')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics_subjects', to='classes.mainclass')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics_subjects_v2', to='tenants.school')),
            ],
            options={
                'unique_together': {('name', 'class_ref')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.exam')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('absent', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='academics.exam')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacherMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='classes.classsection')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_mappings', to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_mappings', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='teachers.teacherprofile')),
            ],
            options={
                'unique_together': {('subject', 'class_section')},
            },
        ),
    ]
