# Generated by Django 5.0.3 on 2026-04-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('classes', '0003_classsection_school_mainclass_school_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='exam',
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name='subject',
                    unique_together=set(),
                ),
                migrations.RemoveField(
                    model_name='result',
                    name='school',
                ),
                migrations.AlterUniqueTogether(
                    name='subjectteachermapping',
                    unique_together={('subject', 'class_section')},
                ),
                migrations.RemoveField(
                    model_name='exam',
                    name='school',
                ),
                migrations.RemoveField(
                    model_name='subject',
                    name='school',
                ),
                migrations.RemoveField(
                    model_name='subjectteachermapping',
                    name='school',
                ),
            ],
            database_operations=[],
        ),
    ]
