# Generated by Django 6.0.3 on 2026-04-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_exam_unique_together_and_more'),
        ('academics', '0002_sync_model_state'),
    ]

    operations = [
    ]
