# Generated by Django 5.0.3 on 2026-04-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_merge_20260408_1337'),
        ('academics', '0003_merge_20260408_1615'),
    ]

    operations = [
    ]
