# Generated by Django 5.0.3 on 2026-04-17 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_merge_20260408_1835'),
        ('classes', '0005_remove_mainclass_shift_classsection_assigned_shift'),
        ('students', '0006_studentprofile_photo'),
        ('teachers', '0009_teacherprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('class_test', 'Class Test'), ('mst', 'MST'), ('final', 'Final')], max_length=30)),
                ('marks', models.FloatField()),
                ('max_marks', models.FloatField(default=100.0)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_entries', to='classes.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_entries', to='students.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_entries', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacherprofile')),
            ],
            options={
                'unique_together': {('student', 'subject', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='ResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('class_test', 'Class Test'), ('mst', 'MST'), ('final', 'Final')], max_length=30)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_statuses', to='classes.classsection')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('class_section', 'exam_type')},
            },
        ),
    ]
