# Generated by Django 5.0.3 on 2026-04-17 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_marks_resultstatus'),
        ('subjects', '0005_fix_teacher_assignment_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_entries', to='subjects.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectTeacherMapping',
        ),
    ]
