# Generated by Django 5.0.3 on 2026-04-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_marks_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('unit_test', 'Unit Test'), ('class_test', 'Class Test'), ('mst', 'MST'), ('final', 'Final')], default='unit_test', max_length=30),
        ),
    ]
