from django.urls import path

from .views import (
    AdminClassFeeCardBootstrapView,
    AdminClassFeeCardBulkUpsertView,
    AdminClassFeeCardFileUploadView,
    AdminClassFeeCardDetailView,
    AdminClassFeeCardListCreateView,
    AdminClassFeeCardDeleteAllView,
    AdminClassFeeCardRollbackView,
    StudentClassFeeCardListView,
    MyFeesView,
    StudentPaymentCreateView,
    StudentReceiptPDFView,
    FeeStructureListCreateView,
    FeeStructureDetailView,
    AdminStudentFeeListView,
    AdminStudentFeeDetailView,
    AdminStudentFeeCreateView,
    AdminSyncClassFeesView,
    AdminPaymentCreateView,
    AdminReceiptPDFView,
    AdminFeesDashboardView,
    AdminFeesCollectionView,
    AdminFeesExportCSVView,
    AdminPaymentReminderView,
)

urlpatterns = [
    path('my/', MyFeesView.as_view(), name='my-fees'),
    path('my/class-fee-cards/', StudentClassFeeCardListView.as_view(), name='student-class-fee-cards'),
    path('my/pay/', StudentPaymentCreateView.as_view(), name='student-pay-create'),
    path('my/receipt/<int:payment_id>/', StudentReceiptPDFView.as_view(), name='student-receipt-pdf'),
    path('admin/dashboard/', AdminFeesDashboardView.as_view(), name='fees-admin-dashboard'),
    path('admin/class-fee-cards/', AdminClassFeeCardListCreateView.as_view(), name='admin-class-fee-cards'),
    path('admin/class-fee-cards/delete-all/', AdminClassFeeCardDeleteAllView.as_view(), name='admin-class-fee-cards-delete-all'),
    path('admin/class-fee-cards/<int:pk>/', AdminClassFeeCardDetailView.as_view(), name='admin-class-fee-card-detail'),
    path('admin/class-fee-cards/upload/', AdminClassFeeCardBulkUpsertView.as_view(), name='admin-class-fee-cards-upload'),
    path('admin/class-fee-cards/upload-file/', AdminClassFeeCardFileUploadView.as_view(), name='admin-class-fee-cards-upload-file'),
    path('admin/class-fee-cards/bootstrap/', AdminClassFeeCardBootstrapView.as_view(), name='admin-class-fee-cards-bootstrap'),
    path('admin/class-fee-cards/rollback/', AdminClassFeeCardRollbackView.as_view(), name='admin-class-fee-cards-rollback'),
    path('collection/', AdminFeesCollectionView.as_view(), name='fees-collection'),
    path('admin/structures/', FeeStructureListCreateView.as_view(), name='fee-structures'),
    path('admin/structures/<int:pk>/', FeeStructureDetailView.as_view(), name='fee-structure-detail'),
    path('admin/student-fees/', AdminStudentFeeListView.as_view(), name='admin-student-fees'),
    path('admin/student-fees/<int:pk>/', AdminStudentFeeDetailView.as_view(), name='admin-student-fee-detail'),
    path('admin/student-fees/create/', AdminStudentFeeCreateView.as_view(), name='admin-student-fee-create'),
    path('admin/sync-class/', AdminSyncClassFeesView.as_view(), name='admin-sync-class-fees'),
    path('admin/payments/', AdminPaymentCreateView.as_view(), name='admin-payment-create'),
    path('admin/receipt/<int:payment_id>/', AdminReceiptPDFView.as_view(), name='admin-receipt-pdf'),
    path('admin/export/csv/', AdminFeesExportCSVView.as_view(), name='fees-export-csv'),
    path('admin/reminder/', AdminPaymentReminderView.as_view(), name='fees-payment-reminder'),
]
