# Generated by Django 5.0.3 on 2026-04-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('classes', '0002_classsection_room_number_mainclass_code_and_more'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='syllabus_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'class_ref',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='classes.mainclass'),
                ),
                (
                    'subject',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='subjects.subject'),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_syllabi', to='teachers.teacherprofile'),
                ),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]

