# Generated by Django 5.0.3 on 2026-04-16 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='pdf',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='file',
            field=models.FileField(default='', upload_to='syllabus_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_syllabi', to=settings.AUTH_USER_MODEL),
        ),
    ]
