# Generated by Django 6.0.3 on 2026-04-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='dealers.dealer'),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
