# Generated by Django 6.0.3 on 2026-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_dealer_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='classes_offered',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='google_map_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_heros/'),
        ),
        migrations.AddField(
            model_name='school',
            name='pass_percentage',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='show_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='show_facilities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='show_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='show_testimonials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='streams',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='total_students_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='total_teachers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
