# Generated by Django 6.0.3 on 2026-04-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_school_address_school_board_school_classes_offered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='show_gallery',
        ),
    ]
