# Generated by Django 5.0.3 on 2026-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_school_show_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_conduct/school_hero/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_conduct/school_logo/'),
        ),
    ]
