# Generated by Django 5.0.3 on 2026-05-03 03:50

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_school_hero_image_alter_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=tenants.models.school_hero_path),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=tenants.models.school_logo_path),
        ),
    ]
