# Generated by Django 6.0.3 on 2026-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacherprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='role',
            field=models.CharField(choices=[('class_teacher', 'Class Teacher'), ('subject_teacher', 'Subject Teacher')], default='subject_teacher', max_length=20),
        ),
    ]
