# Generated by Django 6.0.3 on 2026-04-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_add_teacher_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='role',
        ),
    ]
