# Generated by Django 6.0.3 on 2026-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_remove_teacherprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='role',
            field=models.CharField(choices=[('Class Teacher', 'Class Teacher'), ('Subject Teacher', 'Subject Teacher')], default='Subject Teacher', max_length=20),
        ),
    ]
