# Generated by Django 6.0.3 on 2026-04-21 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teacherprofile_role'),
        ('tenants', '0004_remove_school_show_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.school'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('school', 'employee_id'), name='unique_employee_per_school'),
        ),
    ]
