# Generated by Django 5.0.3 on 2026-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_teacherprofile_school_teacherprofile_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='school_conduct/teacher_documents/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='school_conduct/profile_photo/'),
        ),
    ]
