# Generated by Django 5.0.3 on 2026-05-03 03:36

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_alter_teacherdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.teacher_document_path),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=teachers.models.teacher_photo_path),
        ),
    ]
