# Generated by Django 5.0.3 on 2026-06-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_alter_teacherdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
