# Generated by Django 5.0.3 on 2026-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_teacherprofile_rfid_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='role',
            field=models.CharField(choices=[('Class Teacher', 'Class Teacher'), ('Subject Teacher', 'Subject Teacher'), ('Staff', 'Staff')], default='Subject Teacher', max_length=20),
        ),
    ]
