# Generated by Django 5.0.3 on 2026-06-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_alter_teacherprofile_role'),
        ('timetable', '0013_drop_stale_teacher_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='timetable.shift'),
        ),
    ]
