# Generated by Django 5.0.3 on 2026-07-23 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_teacherprofile_assigned_shift'),
        ('tenants', '0007_alter_school_hero_image_alter_school_logo'),
        ('timetable', '0015_shift_flexible_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('school', 'rfid_code'), name='unique_teacher_rfid_per_school'),
        ),
    ]
