# Generated by Django 5.0.3 on 2026-05-03 03:50

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=gallery.models.gallery_image_path),
        ),
    ]
