# Generated by Django 6.0.3 on 2026-04-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classsection_room_number_mainclass_code_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sections', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='mainclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='mainsection',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.school'),
        ),
        migrations.AlterField(
            model_name='mainclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mainsection',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='mainclass',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='mainsection',
            unique_together={('school', 'name')},
        ),
    ]
