# Generated by Django 5.0.3 on 2026-04-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classsection_school_mainclass_school_and_more'),
        ('timetable', '0009_alter_timetableentry_options_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainclass',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='timetable.shift'),
        ),
    ]
