# Generated by Django 5.0.3 on 2026-04-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_mainclass_shift'),
        ('timetable', '0011_timetableentry_shift_ref_alter_timetableentry_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainclass',
            name='shift',
        ),
        migrations.AddField(
            model_name='classsection',
            name='assigned_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='timetable.shift'),
        ),
    ]
