# Generated by Django 5.0.3 on 2026-04-06 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkimportlog',
            name='imported_users',
            field=models.ManyToManyField(blank=True, related_name='import_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
