# Generated by Django 6.0.3 on 2026-04-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classsection_school_mainclass_school_and_more'),
        ('subjects', '0002_sync_model_state'),
        ('teachers', '0008_remove_teacherprofile_role'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='subjectassignment',
                    name='school',
                ),
                migrations.RemoveField(
                    model_name='subjectnote',
                    name='school',
                ),
                migrations.RemoveField(
                    model_name='teacherassignment',
                    name='school',
                ),
                migrations.AddField(
                    model_name='teacherassignment',
                    name='section',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes.classsection'),
                ),
                migrations.AlterUniqueTogether(
                    name='teacherassignment',
                    unique_together={('teacher', 'class_ref', 'section', 'subject')},
                ),
                migrations.AlterUniqueTogether(
                    name='subject',
                    unique_together={('class_ref', 'name')},
                ),
            ],
            database_operations=[
                # Columns already dropped manually or by previous broken migrations.
                migrations.AddField(
                    model_name='teacherassignment',
                    name='section',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes.classsection'),
                ),
            ],
        ),
    ]
