# Generated by Django 6.0.3 on 2026-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classsection_school_mainclass_school_and_more'),
        ('subjects', '0003_remove_subjectassignment_school_and_more'),
        ('teachers', '0008_remove_teacherprofile_role'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='teacherassignment',
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name='teacherassignment',
                    name='role',
                    field=models.CharField(choices=[('Class Teacher', 'Class Teacher'), ('Subject Teacher', 'Subject Teacher')], default='Subject Teacher', max_length=20),
                ),
                migrations.AlterUniqueTogether(
                    name='teacherassignment',
                    unique_together={('teacher', 'class_ref', 'section', 'subject', 'role')},
                ),
            ],
            database_operations=[
                migrations.AddField(
                    model_name='teacherassignment',
                    name='role',
                    field=models.CharField(choices=[('Class Teacher', 'Class Teacher'), ('Subject Teacher', 'Subject Teacher')], default='Subject Teacher', max_length=20),
                ),
            ],
        ),
    ]
