# Generated by Django 5.0.3 on 2026-03-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(default='School Fee', max_length=100),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
