# Generated by Django 5.0.3 on 2026-03-30 13:05

from django.db import migrations, models


def _has_column(schema_editor, table_name, column_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
                LIMIT 1
                """,
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
        if connection.vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table_name})")
            return any(row[1] == column_name for row in cursor.fetchall())
    return False


def add_due_date_if_missing(apps, schema_editor):
    if _has_column(schema_editor, 'fees_feestructure', 'due_date'):
        return

    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE fees_feestructure ADD COLUMN due_date date NULL")
    elif schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("ALTER TABLE fees_feestructure ADD COLUMN due_date date NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='feestructure',
                    name='due_date',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_due_date_if_missing, migrations.RunPython.noop),
            ],
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(default='School Fee', max_length=100),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
