# Generated by Django 5.0.3 on 2026-03-26 05:31

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def copy_amount_into_breakdown(apps, schema_editor):
    FeeStructure = apps.get_model('fees', 'FeeStructure')
    for fs in FeeStructure.objects.all():
        amt = getattr(fs, 'amount', None)
        if amt is not None:
            fs.tuition_fees = amt
            fs.total_fees = amt
        fs.save()


def dedupe_fee_structure_by_class(apps, schema_editor):
    FeeStructure = apps.get_model('fees', 'FeeStructure')
    StudentFee = apps.get_model('fees', 'StudentFee')
    seen = {}
    for fs in FeeStructure.objects.order_by('id'):
        cid = fs.class_ref_id
        if cid not in seen:
            seen[cid] = fs.id
            continue
        keeper_id = seen[cid]
        StudentFee.objects.filter(fee_structure_id=fs.id).update(fee_structure_id=keeper_id)
        fs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('fees', '0001_initial'),
        ('students', '0002_studentprofile_blood_group_studentprofile_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['class_ref__name']},
        ),
        migrations.AlterModelOptions(
            name='studentfee',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='exam_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tuition_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.RunPython(copy_amount_into_breakdown, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='feestructure',
            name='amount',
        ),
        migrations.RunPython(dedupe_fee_structure_by_class, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feestructure',
            name='class_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='classes.mainclass'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='fees.feestructure'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'fee_structure')},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=32)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfee')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
