# Generated by Django 5.0.3 on 2026-03-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feestructure_options_alter_studentfee_options_and_more'),
        ('fees', '0002_feestructure_due_date_feestructure_fee_type_and_more'),
    ]

    operations = [
    ]
