# Generated by Django 5.0.3 on 2026-03-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_merge_20260331_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='fee_type',
        ),
    ]
